CREATE TABLE GIFTS (
	id VARCHAR(100) PRIMARY KEY,
	title VARCHAR(255) UNIQUE NOT NULL,
	description TEXT,
	url VARCHAR(255),
	multiplicity VARCHAR(50)
);

CREATE TABLE PERSONS (
	id VARCHAR(100) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL
);

